api:
  dashboard: false
  insecure: false

entryPoints:
  web:
    address: ":8780"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: INFO

accessLog:
  filePath: "/dev/stdout"
  format: json
