on:
  workflow_call:
    inputs:
      commitlint-image:
        description: The image for executing commitlint checks
        default: commitlint
        required: false
        type: string
jobs:
  commitlint:
    name: commitlint
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.commitlint-image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: commitlint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
