on:
  workflow_call:
    inputs:
      pre-commit-image:
        description: The image for executing pre-commit checks
        default: pre-commit
        required: false
        type: string
jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.pre-commit-image }}
      # Mount workspace to populate matching path on host (necessary for containerized pre-commit hooks)
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: pre-commit
        env:
          HOME: /root
        run: |
          cd ${{ github.workspace }}
          git config --global --add safe.directory ${{ github.workspace }}
          pre-commit run --show-diff-on-failure --color=always --all-files
